version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: chatbot-fsi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - chatbot-network

  db:
    image: postgres:15
    container_name: chatbot-fsi-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatbot-network

volumes:
  pgdata:

networks:
  chatbot-network:
    driver: bridge
